version: 2

sources:
  - name: chinook
    schema: raw
    description: "Raw chinook data ingested to snowflake"
    tables:
      - name: album
      - name: artist
      - name: customer
      - name: employee
      - name: genre
      - name: invoice
      - name: invoiceline
      - name: mediatype
      - name: playlist
      - name: playlisttrack
      - name: track
